name: Build and Deploy to Aliyun Docker Registry

on:
  push:
    branches:
      - main  # 默认是main分支，你可以根据需要更改

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.ap-southeast-1.aliyuncs.com/whispora/pension:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.ap-southeast-1.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Aliyun Docker Registry
        run: |
          docker push registry.ap-southeast-1.aliyuncs.com/whispora/pension:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/docker-compose &&
            docker compose -f www.yml down
            docker rmi registry.ap-southeast-1.aliyuncs.com/whispora/pension:latest
            docker compose -f www.yml up -d
